package main.com.fing.redstrawberry;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2016-09-22T18:17:05.494-03:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://redstrawberry.fing.com.main/", name = "RedStrawberryWS")
@XmlSeeAlso({ObjectFactory.class})
public interface RedStrawberryWS {

    @WebMethod(operationName = "ProcesarItems")
    @Action(input = "http://redstrawberry.fing.com.main/RedStrawberryWS/ProcesarItemsRequest", output = "http://redstrawberry.fing.com.main/RedStrawberryWS/ProcesarItemsResponse")
    @RequestWrapper(localName = "ProcesarItems", targetNamespace = "http://redstrawberry.fing.com.main/", className = "main.com.fing.redstrawberry.ProcesarItems")
    @ResponseWrapper(localName = "ProcesarItemsResponse", targetNamespace = "http://redstrawberry.fing.com.main/", className = "main.com.fing.redstrawberry.ProcesarItemsResponse")
    public void procesarItems(
        @WebParam(name = "ListaItem", targetNamespace = "")
        java.util.List<main.com.fing.redstrawberry.Item> listaItem
    );
}
