package main.com.fing.redstrawberry;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2016-09-22T18:02:22.082-03:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "RedStrawberryWS", 
                  wsdlLocation = "http://localhost:8080/RedStrawberry/RedStrawberryWS?wsdl",
                  targetNamespace = "http://redstrawberry.fing.com.main/") 
public class RedStrawberryWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://redstrawberry.fing.com.main/", "RedStrawberryWS");
    public final static QName RedStrawberryWSPort = new QName("http://redstrawberry.fing.com.main/", "RedStrawberryWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/RedStrawberry/RedStrawberryWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RedStrawberryWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/RedStrawberry/RedStrawberryWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RedStrawberryWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RedStrawberryWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RedStrawberryWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RedStrawberryWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RedStrawberryWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RedStrawberryWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RedStrawberryWS
     */
    @WebEndpoint(name = "RedStrawberryWSPort")
    public RedStrawberryWS getRedStrawberryWSPort() {
        return super.getPort(RedStrawberryWSPort, RedStrawberryWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RedStrawberryWS
     */
    @WebEndpoint(name = "RedStrawberryWSPort")
    public RedStrawberryWS getRedStrawberryWSPort(WebServiceFeature... features) {
        return super.getPort(RedStrawberryWSPort, RedStrawberryWS.class, features);
    }

}
